version: '3.8'
x-common-variables: &common-variables
  MYSQL_DATABASE: db_project5

services:
  mysql_server:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-pass
      MYSQL_USER: dba
      <<: *common-variables
    secrets:
      - mysql-root-pass
    networks:
      - backend-network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql_server
    depends_on:
      - mysql_server
    networks:
      - backend-network

volumes:
  mysql-data:

networks:
  backend-network:

secrets:
  mysql-root-pass:
    external: true